FROM golang:alpine AS build-env
WORKDIR /usr/local/go/src/{{ .RelDir }}
COPY . /usr/local/go/src/{{ .RelDir }}
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh
RUN go get ./...
RUN go build -o build/{{.Name}} ./{{.Name}}


FROM alpine:latest
RUN apk add --no-cache ca-certificates
COPY --from=build-env /usr/local/go/src/{{ .RelDir }}/build/{{.Name}} /bin/{{.Name}}
CMD ["{{.Name}}", "up"]
