before:
  hooks:
    - go mod download
    - make statik
builds:
  - main: ./lile/main.go
    binary: lile
    env:
    - CGO_ENABLED=0
  - main: ./protoc-gen-lile-server/main.go
    binary: protoc-gen-lile-server
    env:
    - CGO_ENABLED=0
brew:
  name: lile
  github:
    owner: lileio
    name: homebrew-lile
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
