before:
  hooks:
    - go mod download
builds:
  - main: ./lile/main.go
    id: lile
    binary: lile
    env:
    - CGO_ENABLED=0
  - main: ./protoc-gen-lile-server/main.go
    id: protoc-gen
    binary: protoc-gen-lile-server
    env:
    - CGO_ENABLED=0
brews:
  - name: lile
    github:
      owner: lileio
      name: homebrew-lile
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
